spring:
  application:
    name: spring-cloud-ribbon-consumer

server:
  port: 8888

spring-cloud-ribbon-provider:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8090,localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000
